name: Integration 🔀

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Check Prettier formatting
        run: bunx prettier --check .

      - name: Check TypeScript types
        run: bunx tsc --noEmit

      - name: Check Astro types
        run: bunx astro check

      - name: Build test
        run: bun run build

  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Start local server
        run: |
          bun run preview &
          sleep 5
        env:
          CI: true

      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: ./.github/lighthouse/lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
